### ISSUE TITLE
Main window: Make it floatable and resizable

### ISSUE THREAD

**Issue by Aniketh01** [Team-SYNACKd/progressive-streaming#3]
Currently, the main player window is just a static window which basically just plays out the video frames. It should be convenient if the window could be resizable by the user on runtime with a few manageable buttons to close etc.

**Comment by iammarco11** [comment]
I am able to resize the window as well as close it, I quite did not get what you meant by that.

**Comment by Aniketh01** [comment]
how do you close it? I meant to implement a close, resize buttons within the player.

**Comment by iammarco11** [comment]
I quite did not understand, like the window has close and resize buttons. Did you mean the video inside the window should be having a close button and resize button??

**Comment by iammarco11** [comment]
Closing this, fixed in #6
